import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import ToUp from "@/components/ToUp";
import {Inter} from "next/font/google"
import Animatecursor from "@/components/ui/Animate-cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative antialiased`}>
        <Animatecursor/>
        <Navbar />
        <main>
            {children}
        </main>

        {/* <ToUp /> */}
      </body>
    </html>
  );
}
